.TL
X1nigo's Build of DWM

.LP
This is a small document to use in aid of navigation around the system.
What you'll find in here are simple keyboard shortcuts and some
things to note.

.TS
tab(&);
l c l.
MOD + Shift + R & - & restart DWM
MOD + Return & - & terminal (ST)
MOD + P & - & launch DMENU
MOD + W & - & browser (Firefox)
MOD + Q & - & system menu
MOD + B & - & search bookmarks
MOD + Ctrl + B & - & add highlighted item in bookmarks
.TE
