"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""               
 "              
 "   ██╗   ██╗██╗███╗   ███╗██████╗  ██████╗
 "   ██║   ██║██║████╗ ████║██╔══██╗██╔════╝
 "   ██║   ██║██║██╔████╔██║██████╔╝██║     
 "   ╚██╗ ██╔╝██║██║╚██╔╝██║██╔══██╗██║     
 "    ╚████╔╝ ██║██║ ╚═╝ ██║██║  ██║╚██████╗
 "     ╚═══╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
 "              
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""              

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" -- General Settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

 colorscheme default
 syntax on
 set t_Co=256
 set nocompatible

 filetype plugin on
 filetype indent on
 filetype on

 execute  pathogen#infect()

 set number relativenumber
 set shiftwidth=4
 set tabstop=4
 set nobackup
 set incsearch
 set ignorecase
 
" set scrolloff=10
" set cursorline
" set cursorcolumn
" set expandtab
" set nowrap

 set smartcase
 set showcmd
 set showmode
 set showmatch
 set hlsearch
 set history=1000
 set wildmenu
 set wildmode=list:longest
 set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" -- Colors and Theming
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

highlight LineNr	ctermfg=blue	ctermbg=none	cterm=none
highlight Comment	ctermfg=blue	ctermbg=none	cterm=italic
highlight Constant	ctermfg=red	ctermbg=none	cterm=italic
highlight Special	ctermfg=cyan	ctermbg=none	cterm=italic
highlight Statement	ctermfg=cyan	ctermbg=none	cterm=none

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" -- Status Line
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

 set statusline=
 set statusline+=\ %F\ %M\ %Y\ %R
 set statusline+=%=
 set statusline+=\ ascii:\ %b\ hex:\ 0x%B\ row:\ %l\ col:\ %c\ percent:\ %p%%
 set laststatus=2
 let g:airline#extensions#tabline#enabled = 1

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" -- EOF
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
