" Install vim-airline if not already.

if !empty(glob('$HOME/.vim/bundle/vim-airline'))

else
        echom "Installing vim-airline...(1/2)"
        silent !git clone https://github.com/vim-airline/vim-airline ~/.vim/bundle/vim-airline 2>/dev/null
endif

if !empty(glob('$HOME/.vim/autoload/pathogen.vim'))

else
        echom "Installing vim-airline...(2/2)"
        silent !mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim 2>/dev/null
endif

" Color Scheme
colorscheme default

" Syntax / Plugins
execute pathogen#infect()
syntax on
filetype plugin indent on

" Indentation
set autoindent
set expandtab

" Search
set hlsearch
set ignorecase
set incsearch
set smartcase

" Text Rendering
set encoding=utf-8
set linebreak
set wrap

" User Interface
set wildmenu
set number relativenumber
set title
set background=light

" Code Folding
set foldmethod=manual
set foldnestmax=5

" Miscellaneous
set confirm
