#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# These commands need not require sudo before them.
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Check if eza/exa are installed. If so, then use it instead of ls.
[ $(command -v eza) ] && cmd="eza" || cmd="ls"

# Verbose mode for particular commands.
alias \
	rm="rm -Iv" \
	cp="cp -iv" \
	mv="mv -iv"

# For opening/closing encrypted drives.
alias \
	co="sudo cryptsetup open $1 $2" \
	cl="sudo cryptsetup close $1"

# Colorize your commands.
alias \
	ls="$cmd --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	egrep="egrep --color=auto" \
	fgrep="fgrep --color=auto" \
	ip="ip --color=auto" \
	pacman="pacman --color always" \
	diff="diff --color=auto" \
	bat="bat --color=always --style=full"

# Too lazy to type these.
alias \
	merge="xrdb -merge $HOME/.config/x11/xresources" \
	lf="lfuz" \
	df="df -h" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove" \
	xq="xbps-query -Rs" \
	b="bluetoothctl" \
	hs="hugo server --noHTTPCache" \
        m="neomutt" \
	tmr="transmission-remote" \
	bc="bc -ql" \
	rsync="rsync -rtvzP" \
	yt="yt-dlp" \
	yta="yt-dlp -x -f bestaudio/best" \
	z="zathura"
