#!/bin/sh

# These commands need not require sudo before them.
for command in mount umount su poweroff shutdown reboot halt ; do
	alias $command="sudo $command"
done; unset command

# Use alternative if default is unavailable.
[ $(command -v nvim) ] && alias vim="nvim"
[ $(command -v eza) ] && alias ls="eza" || alias ls="ls --color=always"

# Add colors
alias \
	diff="diff --color=always" \
	grep="grep --color=always"

# Verbose mode for particular commands.
alias \
	rm="rm -iv" \
	cp="cp -iv" \
	mv="mv -iv"

# Other commands that need shortcuts.
alias \
	df="df -h" \
	du="du -h" \
	lf="lfup" \
	hs="hugo server --noHTTPCache" \
	tmr="transmission-remote" \
	bc="bc -ql" \
	rsync="rsync -rtvzP" \
	yt="yt-dlp" \
	yta="yt-dlp -x -f bestaudio/best" \
	z="zathura"
