#!/bin/sh

# This is the shrc file; To use this with other shells, just
# create a symlink with the proper renamed file.
# (e.g. bashrc / kshrc)
# ... or just copy the text.

# Know your shell.
case "$0" in
	sh) PS1='$USER@$(hostname -s):$(pwd)>' ;;
	*) PS1='\e[1;33m$USER\e[1;32m@\e[1;34m$(hostname -s):\e[1;35m$(pwd)\e[m>' ;;
esac

set -o emacs

# Load aliases and shortcuts.
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc"

# Edit files under `Home` directory.
ef () {
    clear
    echo "Edit file:"
    file="$(find $HOME -type f | sed "s|$HOME|~|" | fzf --height=20% --reverse --no-separator)"
    file="$(echo "$file" | sed "s|~|$HOME|")"
    backtrack="$(pwd)"
    dir="${file%/*}"

    [ -f "$file" ] && cd "$dir" && $EDITOR "$file" && cd "$backtrack"
    clear
}

# `cd` into your last directory in file-manager.
sff () {
	sf
	cd "$(cat ${XDG_CACHE_HOME:-$HOME/.cache}/sf/.sf_d)"
}
