#!/bin/sh

# This is the shrc file; To use this with other shells, just
# create a symlink with the proper renamed file.
# (e.g. bashrc / kshrc)
# ... or just copy the text.

# Get hostname (sometimes the `hostname` command is not present)
host=$(cat /etc/hostname)
[ -z $host ] && host=voidhost

# Know your shell.
case "$0" in
	sh) PS1='$host:$(pwd)>' ;;
	*) PS1='\e[1;35m$host\e[m\e[1m:$(pwd)>\e[m' ;;
esac

set -o emacs

# Load aliases and shortcuts.
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc"

# Edit files under `Home` directory.
ef () {
    clear
    echo "Edit file:"
    file="$(find $HOME -type f | sed "s|$HOME|~|" | fzf --height=20% --reverse --no-separator)"
    file="$(echo "$file" | sed "s|~|$HOME|")"
    backtrack="$(pwd)"
    dir="${file%/*}"

    [ -f "$file" ] && cd "$dir" && $EDITOR "$file" && cd "$backtrack"
    clear
}

# `cd` into your last directory in file-manager.
fmcd () {
	fm
	cd "$(cat ${XDG_CACHE_HOME:-$HOME/.cache}/fm/.fm_d)"
}
