#!/bin/sh

# Increases autorepeat rate.
xset r rate 300 50
xrandr --dpi 96
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources

# Autostart function that avoids duplication.
autostart="mpd dunst setbg xcompmgr dwmblocks pipewire transmission-daemon"
for program in $autostart; do
	pgrep -x "$program" || "$program" &
done >/dev/null 2>&1

# Start the window manager.
while true; do ssh-agent dwm; done
