#! /bin/sh

modes=( "anemone" "blot" "demon" "galaxy" "matrix" \
	"pacman" "rain" "scooter" "space" "worm" )

list_choices() {
	for i in ${modes[@]}; do
		echo $i
	done
}

lockthis=$(list_choices | dmenu -p "Lock Screen Mode: " -l ${#modes[@]})

case $lockthis in
	${modes[0]}) xlock -mode ${modes[0]} ;;
	${modes[1]}) xlock -mode ${modes[1]} ;;
	${modes[2]}) xlock -mode ${modes[2]} ;;
	${modes[3]}) xlock -mode ${modes[3]} ;;
	${modes[4]}) xlock -mode ${modes[4]} ;;
	${modes[5]}) xlock -mode ${modes[5]} ;;
	${modes[6]}) xlock -mode ${modes[6]} ;;
	${modes[7]}) xlock -mode ${modes[7]} ;;
	${modes[8]}) xlock -mode ${modes[8]} ;;
	${modes[9]}) xlock -mode ${modes[9]} ;;
esac
